### PR TITLE
Add Person entity domain objects for use by Jackson de/serialization

### PR DESCRIPTION
**Pull request by hlbraddock**
@frett

### CODE REVIEW

**Comment by frett** [comment]
Some of the reason I didn't originally include models of various entities (e.g. Person) was because their definitions are incredibly dynamic, which makes the model a constant moving target. Plus, most systems cares about different fields on the entities, so I was figuring it would be more beneficial for a system to define their own entity models based on what they actually want to consume from/push to the GR.

For example, your current Person model doesn't include the key_guid or relay_guid fields, which I think would be something commonly used across the board. It also doesn't include anything about entity relationships. So, including the Person model would be beneficial for relay services (where you pulled the definition from), but that model would be worthless for most other clients and they would either have to end up defining their own model, or constantly be making adjustments to the provided models to meet their specific use cases.

I know for ruby there is a separate global_registry_models library that contains common entity models (https://github.com/CruGlobal/global_registry_models). I like that concept because it's an optional dependency a client isn't forced to include and can be iterated independently. At a bare minimum I would want the entity models in a separate module within this library, I'm not sure if I would want to go to the extreme of putting the models in a completely independent library.

With that said I'm definitely not opposed to including models for the non-dynamic system types (e.g. Notification object models). Although, I'm not sure how you are intending to use them in conjunction with the rest of this API library other than just using the library as a storage spot for your models. Everything currently in this API client is based around the pull API and nothing in it is setup for the push notifications system. Maybe you could include some parsing logic on the serializer that takes the raw notification data and returns your parsed notification object, that's probably the most reusable way to handle notifications.

**Comment by hlbraddock** [comment]
Those are good points. And I'm open to retaining client side.

What precipitated this was my needing these same entities in https://github.com/CruGlobal/ert-api, as I'd used in https://github.com/CruGlobal/relay-services, and I thought a common shared repository seemed appropriate.

If we did move them to a shared repo, following the guidelines you suggest (e.g. separate module in https://github.com/GlobalTechnology/global-registry-java-client), I would assume we'd keep the `Person` entity, and any other we'd like to include, iteratively up to date, and could add any, as necessary, depending on client interest, such as`authentication` (which I'd most likely want to add).

I'm not actually using the notification entities anywhere yet other than https://github.com/CruGlobal/relay-services, but I'd thought they might prove useful for other clients at some point. 

Ultimately, I'm just wanting to prevent multiple clients from writing the same code. If you think that won't be the case then, as I say, I'm entirely amenable to retaining client side.

**Comment by frett** [comment]
let's get the entity models in as a separate entities-jackson module so you can proceed with your current use-case (I have a maven directory idea I want to try out for it, so I'll make the maven changes for that on your branch).

for notifications since it isn't being used anywhere else at the moment let's postpone it.

**Comment by hlbraddock** [comment]
By the way, when I say ' I would assume we'd keep the Person entity, and any other we'd like to include, iteratively up to date,', I really should be saying, that's something that the contributors to this repository will have to assume responsibility for maintaining.

**Comment by frett** [comment]
I moved the entities to a `global-registry-client-entities-jackson` module, and switched to using Google Guava (which we were already importing) instead of `commons-lang`

**Comment by hlbraddock** [comment]
I had actually removed the commit for entity notification and force pushed (or so I'd thought). Did you put it back in intentionally?

**Comment by frett** [comment]
nope, was working off a stale copy when I made my changes

**Comment by hlbraddock** [comment]
This looks good. +1 I'll merge.

**Comment by frett** [comment]
after it's merged I'll get the SNAPSHOT artifacts up on our maven repo, and I'll try to get travis instrumented to do automatic snapshot builds sometime soon.

**Pull request merged**
