### PR TITLE
Java 6 compatible

### PR DESCRIPTION
**Pull request by wrandall22**
This PR makes the global registry java client Java 6 compatible. The main things were:
 * Removing diamond notation
 * Going back to try/catch/finally blocks instead of using `AutoCloseable` objects
 * Changing `switch(String)` blocks to if/else blocks

### CODE REVIEW

**Comment by wrandall22** [comment]
@frett here's that change. I want to make sure the try/catch/finally blocks were converted over as they were intended (I haven't actually done any AutoCloseable code before, but I think I converted it over correctly).

**Comment by wrandall22** [comment]
Switched to use Guava Objects

**Comment by frett** [comment]
added a few comments.

I know there is a google guava object to emulate the try-with-resources paradigm. But I haven't looked into it too heavily to know how to use it or if it's worth using in this scenario.

**Comment by frett** [comment]
https://github.com/google/guava/wiki/ClosingResourcesExplained

**Comment by frett** [comment]
I would say don't worry about utilizing `Closer` in the tests, but utilize it in the library code itself, especially where we have multiple streams being handled together

**Comment by wrandall22** [comment]
Implemented Closer.

**Comment by frett** [comment]
+1

**Comment by wrandall22** [comment]
Thanks for the review!

**Comment by mattdrees** [comment]
@wrandall22 I don't remember this well. Was this only for SSW and/or WSAPI, which I think might have been using java 6 at that point in time?

Those are using java 8 now, so I'm wondering if it's worth reverting this.

**Comment by wrandall22** [comment]
@mattdrees I found an email chain showing this change was meant for WSAPI specifically. So, I think this can be reverted.

**Pull request merged**
